---
name: "Bug report"
description: Create a report to help us improve
labels: "bug"
body:
- type: markdown
  attributes:
    value: |
      Before you submit a new bug report, please check the [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request).
      Also, please search through the existing issues to see if others have had the same problem.
- type: textarea
  attributes:
    label: "Describe the bug"
    description: "Please provide a clear and concise description of what the bug is. Steps to reproduce.
    If this is an issue with the sensor state or translation, please go to Developer Tools/States, 
    find the entity under Current entities, 
    click on the sensor's (i) icon and check the status in the right top corner. 
    Most (if not all) issues reported with status were related to the Lovelace config, 
    not the actual sensor state. So this will save both of us lots of time."
  validations:
    required: true
- type: textarea
  attributes:
    label: "Configuration"
    description: "Copy the device configuration below.
    Go to the device (e.g. from Configuration / Devices & Services, select the integration and the device.)
    Hit DOWNLOAD DIAGNOSTICS, and paste the content of the file below."
  validations:
    required: true
- type: textarea
  attributes:
    label: "Debug logs"
    description: "Copy the error message from Developer tools/Logs below.
    To enable debug logging, add `custom_components.garbage_collection: debug` 
    to your `configuration.yaml` under `logger/logs`."
    render: text
  validations:
    required: true
