collect_garbage:
  description: Set the last_collection attribute to the current date and time.
  fields:
    entity_id:
      description: The garbage_collection sensor entity_id
      example: sensor.general_waste
