name: Validate code

on:
  push:
  pull_request:

jobs:
  hassfest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: home-assistant/actions/hassfest@master
  isort_black_flake8:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install 'isort==5.*' black flake8
      - name: Change directory
        run: cd custom_components/garbage_collection
      - name: isort
        run: isort -l88 -tc -m 3 -c .
      - name: black
        run: black --check .
      - name: flake8
        run: flake8 --max-line-length 88 --extend-ignore E501 .
  bandit:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: Bandit Check (Python security linter)
        uses: jpetrucciani/bandit-check@master

