blueprint:
  name: Include dates
  description: >-
    Add collection on set of additional collection dates. Enter one date per line. For example:

    2022-01-03

    2022-04-04

    2022-07-04

    2022-10-03

    After updating the list, make sure to trigger the entity update. 
    The sensors are normally updated once a day, or when Home Assistant starts.
    The update can be triggered by updating the integration configuration (just hit configure and submit).
  domain: automation
  source_url: https://github.com/bruxy70/Garbage-Collection/blob/master/blueprints/include.yaml
  input:
    garbage_collection_entity:
      name: Garbage Collection Entity
      description: Triggered by the event for this entity.
      selector:
        entity:
          integration: garbage_collection
    include:
      name: Set of dates to include
      description: |-
        List of dates in format yyyy-mm-dd, one date per line.
      selector:
        text:
          multiline: true
mode: parallel
trigger:
  - platform: event
    event_type: garbage_collection_loaded
    event_data:
      entity_id: !input garbage_collection_entity
action:
  - variables:
      include: !input include
  - repeat:
      count: "{{ include.split('\n') | count }}"
      sequence:
        - service: garbage_collection.add_date
          data:
            entity_id: "{{ trigger.event.data.entity_id }}"
            date: "{{ include.split('\n')[repeat.index-1] }}"
  - service: garbage_collection.update_state
    data:
      entity_id: "{{ trigger.event.data.entity_id }}"
